#!/bin/bash

(
	cd ~/chef/cookbooks/byobu/ \
		&& sed --in-place "s/version '0.1.[0-9][0-9]*'/version '0.1.$(echo $(( $(awk -F. '/version/{print $NF}' metadata.rb | sed 's/[^0-9]//g') + 1)))'/" metadata.rb
		berks install
		berks upload
)
